backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: site
    label: Site Content
    files:
      - file: src/content/site.json
        label: Website Content
        name: content
        fields:
          - {label: Site Name, name: siteName, widget: string}
          - {label: Hero Title, name: heroTitle, widget: string}
          - {label: Hero Text, name: heroText, widget: text}
